ERROR - 2023-05-28 12:34:02 --> mysqli_sql_exception: Table 'belajarci.users' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/MySQLi/Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/belajarci/app/Database/Seeds/UserSeeder.php(18): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/Seeder.php(146): App\Database\Seeds\UserSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Commands/Database/Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/CLI/Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/CLI/Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/belajarci/spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
ERROR - 2023-05-28 12:36:17 --> mysqli_sql_exception: Table 'belajarci.users' doesn't exist in /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/MySQLi/Connection.php:295
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/MySQLi/Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 /Applications/XAMPP/xamppfiles/htdocs/belajarci/app/Database/Seeds/UserSeeder.php(18): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Database/Seeder.php(146): App\Database\Seeds\UserSeeder->run()
#6 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/Commands/Database/Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/CLI/Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#8 /Applications/XAMPP/xamppfiles/htdocs/belajarci/system/CLI/Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/belajarci/spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
CRITICAL - 2023-05-28 13:20:55 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:20:57 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:20:57 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:21:04 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:21:07 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:21:08 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:21:09 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:21:40 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 13:29:38 --> Cannot declare class App\Filters\AuthMiddleware, because the name is already in use
in APPPATH/Config/Filters.php on line 9.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-05-28 16:44:59 --> Credentials is invalid!
in APPPATH/Controllers/Login.php on line 66.
 1 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Login->create()
 2 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 3 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
